name: applite_solutions
description: "A new Flutter project."
publish_to: 'none'

version: 0.0.8

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  #Platform Dependencies Start---
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  get: ^4.6.6
  delightful_toast: ^1.1.0
  cached_network_image: ^3.3.1
  html: ^0.15.0
  readmore: ^3.0.0
  gradient_borders: ^1.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_launcher_icons: ^0.13.1
#Platform Dependencies End---

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2


flutter:

  uses-material-design: true

  assets:
    - assets/
flutter_intl:
  enabled: true

